image: python2.7
script: 
  - sudo apt-get update
  - sudo apt-get -y install libguestfs-tools sqlite3 python-pip python-dev build-essential
  - pip install -r requirements.txt
  - python manage.py test
notify:
  email:
    recipients:
      - kevin@stealsyour.pw
  irc:
    channel: managrr-dev 
    nick: ManagrrBot 
    server: "irc.freenode.net:6667"
    on_started: true
    on_success: true
    on_failure: true

