image: python2.7
script: 
  - sudo apt-get -y install sqlite3 python-pip python-dev build-essential 1> /dev/null 2> /dev/null
  - pip install -r requirements.txt
  - python manage.py test
notify:
  email:
    recipients:
      - kevin@stealsyour.pw
  irc:
    channel: capstone 
    nick: Craig 
    server: "irc.arcti.cc:6697"
    on_started: true
    on_success: true
    on_failure: true

