language: python
python:
  - "2.7"
# command to install dependencies
install: "python manage.py install"
# command to run tests
script: python manage.py test

# whitelist
branches:
  only:
    - master
    - dev
